DPO-3436 Korvataan ESLint BiomeJS:llä (#90)
* DPO-3436 Korvataan ESLint BiomeJS:llä
- Configs
- Workflow

diff --git a/lefthook.yml b/lefthook.yml
--- a/lefthook.yml
+++ b/lefthook.yml
@@ -8,11 +8,15 @@ pre-commit:
   commands:
     01-sort-package-json:
       #glob: "*.{ts,yml,yaml,md,json,html}"
-      run: | # Reorder package.json
-        pnpm run sort:package-json;
-        git add package.json || true;
-    02-deno-fmt:
+      run: |
+        # Reorder package.json
+        pnpm run sort:package-json
+        # Re-add package.json if it was modified
+        git add package.json || true
+    02-biomejs-check:
       #glob: "*.{ts,yml,yaml,md,json,html}"
-      run: | # Runs even when deno fmt fails with: No target files found.
-        pnpm run run:format -- {staged_files} || true;
-        git add {staged_files} || true;
+      run: |
+        # Run Biome on staged files, auto-fixing issues
+        pnpm format:fix-staged || true;
+        # Re-add any files that Biome fixed. Sometimes deleted files cause git add to fail, so we ignore errors.
+        git add $(git diff --name-only --cached) || true
